name: fl_amap_map
description: AMap Map plugin for flutter
version: 0.0.1
repository: https://github.com/Wayaer/fl_amap_map.git

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: fl.amap.map
        pluginClass: FlAMapMapPlugin
      ios:
        pluginClass: FlAMapMapPlugin
